### ISSUE TITLE
start.py seems to not function properly under python 3

### ISSUE THREAD

**Issue by fedorov** [modelhub-ai/modelhub#35]
![image](https://user-images.githubusercontent.com/313942/43286726-f4e1b1e8-90f0-11e8-84e9-29f6d516aa3b.png)

**Comment by michaelschwier** [comment]
This issue only appears under Python 3.5 (and possibly lower), Python 3.6 works fine on mac (notice, however, that on mac you have to install SSL certificates for Python, see infos during install, Python 3.6 comes with an install script for certificates under "Applications/Python 3.6").

I'll see if I can easily fix this to make it compatible with 3.5 and 3.6 but overall I would advice against trying to support old Python versions.

**Comment by michaelschwier** [comment]
I could fix it such that the list works under Python 3.5 as well. But on my test Mac Python 3.5 still has trouble downloading due to SSL issues (not up to date on mac). Using Python 3.6 with the above mentioned certificate update seems to work. I added an error printout to the start script, in case someone is using an old python, asking them to update.
