### ISSUE TITLE
start.py to update docker image eben with same tag

### ISSUE THREAD

**Issue by ahmedhosny** [modelhub-ai/modelhub#44]
something like -uc to update contrib src and -ud to update docker (both optional)

**Comment by michaelschwier** [comment]
Done. option is "-ud". I left the other at "-u" since this is usually the kind of update you want to run (and if the contrib_src requires a new version - indicated by a new tag - it will donwload that automatically. The -ud is for very special cases in which we didn't update the tag but in fact changed the docker (e.g. bugfix).

I'm still wondering if it wouldn't be better to actually change the tag version number of the docker if we do changes to a docker ... that would make this option obsolete. But let's close this for now, it doesn't hurt to have this option :)
